CC					:=	cc
CFLAGS				:=	-Wall -Wextra -Werror -D READLINE_LIBRARY
NAME				:=	minishell

RM					:=	rm
RMFLAGS				:=	-f

SRCS_DIR			:=	src


LIBFT_DIR			:=	libft
LIBFT				:=	$(LIBFT_DIR)/libft.a

$(LIBFT)			:
	make -C $(LIBFT_DIR) all